### ISSUE TITLE
Support for IQueryable?

### ISSUE THREAD

**Issue by ngcammayo** [cmatskas/EF.GenericRepository#1]

**Comment by cmatskas** [comment]
Hi ngcammayo, would you care to elaborate a little bit so that I can see if I can help you? What are you trying to achieve? Thanks, CM

**Comment by ngcammayo** [comment]
```
    public IQueryable<TEntity> GetPage( int pagePar, int pageSizePar, out int totalCount)
    {
        page = pagePar;
        pageSize = pageSizePar;
        totalCount = repository.Get(filter).Count();

        return repository.Get(filter, orderByQuerable, includeProperties, page, pageSize);
    }

    public IQueryable<TEntity> Get()
    {
        return repository.Get(filter, orderByQuerable, includeProperties, page, pageSize);
    }
```

**Comment by ngcammayo** [comment]
I figured it out CM, thanks. I just need to exposed the IQueryable like what you did with the IEnumerable and because your IQueryable is only internal in the Repository class. Will use that in many custom implementation of linq queries such as server side paging.

**Comment by cmatskas** [comment]
I'm really glad you worked it out in the end :)
